language: java
jdk:
 - oraclejdk8
install: true

addons:
  sonarcloud:
    organization: nineclown-github
    token:
      secure: 20cccee07ce13984260fc360c226cdc1ad1b0ed5

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file_glob: true
  file: $HOME/.m2/repository

  skip_cleanup: true
  on:
    tags: true

before_install:
  - chmod +x gradlew

script:
  # ./gradlew clean check sonarqube build
  - ./gradlew clean check build
  - sonar-scanner

cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
    
