language: java
jdk:
 - oraclejdk8
install: true

addons:
  sonarcloud:
    organization: nineclown-github
    token:
      secure: 20cccee07ce13984260fc360c226cdc1ad1b0ed5

#before_deploy: "grunt deploy"

deploy:
  provider: releases
  api_key:
    secure: "GITOKEN"
  file_glob: true
  file: "/home/travis/*"
  skip_cleanup: true
  on:
    repo: Nineclown/sonarqube-test
    tags: false

before_install:
  - chmod +x gradlew

script:
  # ./gradlew clean check sonarqube build
  - ./gradlew clean check build
  - sonar-scanner

cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.gradle
    .gradle
    
